version: '3.8'
 
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    environment:
      - DB_HOST=sqlserver
      - DB_USER=API_user
      - DB_PASSWORD=loulou49
      - DB_NAME=ProjetSQLserver
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrongPassword!
    volumes:
      - sqlserverdata:/var/opt/mssql
 
volumes:
  sqlserverdata: